load("@bazel_skylib//rules:native_binary.bzl", "native_test")
load("@package_metadata//rules:package_metadata.bzl", "package_metadata")
load("@rules_python//python/uv:lock.bzl", "lock")

# gazelle:map_kind py_library py_library @aspect_rules_py//py:defs.bzl
# gazelle:map_kind py_binary py_binary @aspect_rules_py//py:defs.bzl
# gazelle:map_kind py_test py_test @aspect_rules_py//py:defs.bzl

package_metadata(
    name = "package_metadata",
    purl = "pkg:bazel/{}@{}".format(
        module_name(),
        module_version(),
    ),
    visibility = ["//visibility:public"],
)

lock(
    name = "requirements",
    srcs = ["pyproject.toml"],
    out = "requirements.txt",
)

native_test(
    name = "requirements_test",
    src = "requirements.update",
)
